In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [4]:
cols_for_delete = ['Name', 'Ticket', 'Cabin']

In [5]:
df = df.drop(cols_for_delete, axis=1)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Fare         891 non-null    float64
 8   Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 62.8+ KB


In [7]:
dummies = []
cols = ['Pclass', 'Sex', 'Embarked']
for col in cols:
    dummies.append(pd.get_dummies(df[col]))

In [8]:
titanic_dummies = pd.concat(dummies, axis=1)

In [9]:
titanic_dummies

1      2      3  female   male      C      Q      S
0    False  False   True   False   True  False  False   True
1     True  False  False    True  False   True  False  False
2    False  False   True    True  False  False  False   True
3     True  False  False    True  False  False  False   True
4    False  False   True   False   True  False  False   True
..     ...    ...    ...     ...    ...    ...    ...    ...
886  False   True  False   False   True  False  False   True
887   True  False  False    True  False  False  False   True
888  False  False   True    True  False  False  False   True
889   True  False  False   False   True   True  False  False
890  False  False   True   False   True  False   True  False

[891 rows x 8 columns]

In [10]:
df = pd.concat((df, titanic_dummies), axis=1)

In [11]:
df = df.drop(cols, axis=1)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Age          714 non-null    float64
 3   SibSp        891 non-null    int64  
 4   Parch        891 non-null    int64  
 5   Fare         891 non-null    float64
 6   1            891 non-null    bool   
 7   2            891 non-null    bool   
 8   3            891 non-null    bool   
 9   female       891 non-null    bool   
 10  male         891 non-null    bool   
 11  C            891 non-null    bool   
 12  Q            891 non-null    bool   
 13  S            891 non-null    bool   
dtypes: bool(8), float64(2), int64(4)
memory usage: 48.9 KB


In [13]:
df['Age'] = df['Age'].interpolate()

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Age          891 non-null    float64
 3   SibSp        891 non-null    int64  
 4   Parch        891 non-null    int64  
 5   Fare         891 non-null    float64
 6   1            891 non-null    bool   
 7   2            891 non-null    bool   
 8   3            891 non-null    bool   
 9   female       891 non-null    bool   
 10  male         891 non-null    bool   
 11  C            891 non-null    bool   
 12  Q            891 non-null    bool   
 13  S            891 non-null    bool   
dtypes: bool(8), float64(2), int64(4)
memory usage: 48.9 KB


In [15]:
x = df.values
y = df['Survived'].values

In [16]:
x = np.delete(x, 1, axis=1)

In [17]:
x

array([[1, 22.0, 1, ..., False, False, True],
       [2, 38.0, 1, ..., True, False, False],
       [3, 26.0, 0, ..., False, False, True],
       ...,
       [889, 22.5, 1, ..., False, False, True],
       [890, 26.0, 0, ..., True, False, False],
       [891, 32.0, 0, ..., False, True, False]], dtype=object)

In [39]:
from sklearn.model_selection import train_test_split

In [41]:
X_train, X_test, Y_train, Y_train = train_test_split(x, y, random_state=0, test_size=0.3)

In [43]:
X_train

array([[858, 51.0, 0, ..., False, False, True],
       [53, 49.0, 1, ..., True, False, False],
       [387, 1.0, 5, ..., False, False, True],
       ...,
       [630, 53.0, 0, ..., False, True, False],
       [560, 36.0, 1, ..., False, False, True],
       [685, 60.0, 1, ..., False, False, True]], dtype=object)

In [45]:
X_test

array([[496, 37.5, 0, ..., True, False, False],
       [649, 39.5, 0, ..., False, False, True],
       [279, 7.0, 4, ..., False, True, False],
       ...,
       [621, 27.0, 1, ..., True, False, False],
       [787, 18.0, 0, ..., False, False, True],
       [65, 12.333333333333334, 0, ..., True, False, False]], dtype=object)